language: minimal
dist: bionic

git:
  quiet: true

addons:
  apt:
    sources:
    - sourceline: 'deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_18.04/ /'
      key_url: 'https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/xUbuntu_18.04/Release.key'
    update: true
    packages:
    - buildah

script:
- echo $quayiopassword | buildah login -u $quayiouser --password-stdin quay.io
- sudo ./run.sh

after_success:
- buildah push buildah-vfs:latest docker://quay.io/$quayiouser/buildah-vfs:latest

after_script:
- buildah logout quay.io
